// Desktop binary entry point. All app logic lives in the library crate
// (`src/lib.rs`), which is also what cargo-makepad compiles into the Android
// cdylib (`.so`). Keeping the entry thin means desktop and Android share the
// exact same code; only the launch shim differs.
//
// On Android there is no `fn main` — the Java shim loads the cdylib and calls the
// JNI `android_main` generated by `app_main!` in the library.
#[cfg(not(target_os = "android"))]
fn main() {
    // Headless SSH self-test (no GUI): `leuwi-panjang ssh-smoke [list|attach [session]]`.
    // Exercises the exact SSH → tmux path the Android app uses; see src/ssh.rs.
    let args: Vec<String> = std::env::args().collect();
    if args.get(1).map(|s| s.as_str()) == Some("ssh-smoke") {
        let sub = args.get(2).map(|s| s.as_str()).unwrap_or("list");
        let session = args.get(3).map(|s| s.as_str()).unwrap_or("main");
        leuwi_panjang::ssh::smoke(sub, session);
        return;
    }
    // Ignore SIGINT — Ctrl+C should go to PTY, not kill terminal.
    #[cfg(unix)]
    unsafe {
        libc::signal(libc::SIGINT, libc::SIG_IGN);
    }
    leuwi_panjang::app_main()
}
